import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import BookCard from '../components/book-card'
import CategoryButton from '../components/category-button'
import Container from '../components/container'
import { getCategories, getBooks } from '../services/books-api'
import { Book } from '../types/book'
import Category from '../types/category'

const Home: NextPage = () => {
  const [categories, setCategories] = useState<Category[]>([]);
  const [books, setBooks] = useState<Book[]>([]);
  const [activeCategory, setActiveCategory] = useState<number>();

  useEffect(() => {
    getCategoriesData();
  }, []);

  useEffect(() => {
    if (activeCategory) {
      getBookData(activeCategory);
    }
  }, [activeCategory]);

  
  const getCategoriesData = async () => {
    try {
      const [categories] = await getCategories();
      console.log(categories)
      setCategories(categories);
    } catch (e) {
      console.error(e);
    }
  };
  
  const getBookData = async (categoryId: number) => {
    try {
      const [books] = await getBooks(categoryId);
      console.log(books)
      setBooks(books);
    } catch (e) {
      console.error(e);
    }
  };

  const handleClickCategory = (id: number) => {
    setActiveCategory(id);
  }

  return (
    <div>
      <Head>
        <title>Sejutacita Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <Container>
          <h2 className="text-xl font-bold mb-4">sejutacita</h2>
          <div className="flex flex-wrap mb-4">
            {categories?.map(category => (
              <CategoryButton key={name} data={category} isActive={activeCategory === category.id} onClick={handleClickCategory} />
            ))}
          </div>
          <div className="grid grid-cols-2 md:grid-cols-5 gap-8">
            {/* <pre>{JSON.stringify(books, "", 2)}</pre> */}
            {books?.map(book => (
              <BookCard key={book.id} data={book} />
            ))}
          </div>
        </Container>
      </main>
    </div>
  )
}

export default Home
